package com.myproject.elearning.exception;

import static com.myproject.elearning.web.rest.utils.ResponseUtils.wrapErrorResponse;

import com.myproject.elearning.dto.common.ApiResponse;
import com.myproject.elearning.exception.problemdetails.EmailAlreadyUsedException;
import com.myproject.elearning.exception.problemdetails.InvalidIdException;
import com.myproject.elearning.exception.problemdetails.TokenException;
import java.net.URI;
import java.util.List;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.authorization.AuthorizationDeniedException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;

/**
 * Here the key phrases are:
 * status: HTTP status code generated by the server.
 * type: A URL that identifies the problem type and how to mitigate it. The default value is – about:blank.
 * title: A short summary of the problem.
 * detail: Problem explanation specific to this occurrence.
 * instance: URL of the service where this problem occurred. The default value is the current request URL.
 * <a href="https://howtodoinjava.com/spring-mvc/spring-problemdetail-errorresponse/">...</a>
 */
@RestControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(value = Exception.class)
    public ResponseEntity<ProblemDetail> handleAnyException(Exception ex, WebRequest request) {
        ProblemDetail problemDetail = getProblemDetail(ex);
        return ResponseEntity.status(problemDetail.getStatus()).body(problemDetail);
    }

    private ProblemDetail getProblemDetail(Throwable ex) {
        if (ex instanceof TokenException te) {
            return te.getBody();
        } else if (ex instanceof InvalidIdException iie) {
            return iie.getBody();
        } else if (ex instanceof EmailAlreadyUsedException eaue) {
            return eaue.getBody();
        } else if (ex instanceof MethodArgumentNotValidException manve) {
            manve.getBody().setProperty("errors", getFieldErrors(manve));
            return manve.getBody();
        }
        return getDefaultProblemDetail(ex);
    }

    @ExceptionHandler({AccessDeniedException.class, AuthorizationDeniedException.class})
    public ResponseEntity<ApiResponse<ProblemDetail>> handleSecurityException(Exception ex) {
        ProblemDetail problemDetail = ProblemDetail.forStatus(HttpStatus.FORBIDDEN);
        problemDetail.setTitle("Access Denied");
        problemDetail.setDetail(ex.getMessage());

        ApiResponse<ProblemDetail> response = wrapErrorResponse("Access denied to this resource", problemDetail);

        return ResponseEntity.status(HttpStatus.FORBIDDEN).body(response);
    }

    private ProblemDetail getDefaultProblemDetail(Throwable ex) {
        ProblemDetail problemDetail = ProblemDetail.forStatus(HttpStatus.INTERNAL_SERVER_ERROR);
        problemDetail.setType(URI.create("about:blank"));
        problemDetail.setTitle("An error occurred");
        problemDetail.setDetail(ex.getMessage());
        return problemDetail;
    }

    private List<String> getFieldErrors(MethodArgumentNotValidException ex) {
        return ex.getBindingResult().getFieldErrors().stream()
                .map(f -> f.getField() + ": " + f.getDefaultMessage())
                .toList();
    }
}
