spring:
  application:
    name: elearning

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/elearning?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      repositories:
        enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


jwt:
  base64-secret: gNvW6uq3Ky9//vVtvLHexnQ9c5rhR/pE6uPz/OFZ02tke+j4s6ukyY2YwMIj1a5ERhwR1oYPwlRAZvNCDoAjHw
  access-token-expiration: 2592000
  refresh-token-expiration: 2592000
  token-refresh-threshold: 300000

file:
  folder_uri: D:/work/temp

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    websocket-sessions:
      enabled: true
    health:
      show-details: always
  security:
    enabled: false

#logging:
#  level:
#    org.springframework.jdbc.core: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG

meilisearch:
  host: http://localhost:7700
  master-key: MASTER_KEY_123
